name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Setup
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - uses: pnpm/action-setup@v4.0.0
      with:
        version: 9
        run_install: |
            args: [--no-frozen-lockfile]
    - name: Typecheck
      run: |
        pnpm build-types
        pnpm link .
        pnpm typecheck
    - name: Lint
      run: |
        pnpm lint
    - name: Test
      env:
        CI: true
      run: |
        pnpm test -- --ci --coverage
    - name: Report
      if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
      env:
        COVERALLS_GIT_BRANCH: ${{ github.ref }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        pnpm coveralls
    - name: Build
      run: |
        pnpm build
        cd ./demo
        make build
        cd ../
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: matrix.node-version == '20.x' && github.ref == 'refs/heads/main' && github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./demo/build
        publish_branch: demo
    - name: Release
      if: matrix.node-version == '20.x' && github.ref == 'refs/heads/main' && github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        pnpm release
